import { Toaster } from "sonner";
import "./global.css";

export const metadata = {
  title: "Welcome to web-content-monitor",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
